server:
  port: 9000

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG


spring:
  datasource:
    #    下面四项为jdbc的通用配置，也可以放在druid标签下
    url: jdbc:mysql://127.0.0.1:3306/qingning
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 123456
    password: Aa123456

    #druid配置
    druid:
      # 初始化连接大小
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 3000000
      # 测试连接
      validation-query: SELECT 1 FROM DUAL
      # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      # 获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      # 归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      # 开启poolPreparedStatements 后生效
      max-pool-prepared-statement-per-connection-size: 20
      # 配置扩展插件，常用的插件有 -> stat:监控统计  wall:防御sql注入
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能;慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


##druid监控配置（StatViewServlet 配置）

      stat-view-servlet:
        # 是否开启内置监控页面，默认值为 false
        enabled: true
        # StatViewServlet 的映射路径，即内置监控页面的访问地址
        url-pattern: /druid/*
        # 是否启用重置按钮
        reset-enable: true
        # 内置监控页面的登录页用户名 username
        login-username: druid
        # 内置监控页面的登录页密码 password
        login-password: druid

      # WebStatFilter 配置
      web-stat-filter:
        # 是否开启内置监控中的 Web-jdbc 关联监控的数据
        enabled: true
        # 匹配路径
        url-pattern: /*
        # 是否监控session
        session-stat-enable: true
        # 排除路径
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"


# Spring 监控配置
# Spring监控AOP切入点，如x.y.z.abc.*, 配置多个英文逗号分隔
      aop-patterns: com.example.*
        
#可以通过 spring.datasource.druid.filters=stat,wall ... 的方式来启用相应的内置 Filter，
#不过这些 Filter 使用的都是默认配置。如果默认配置不能满足我们的需求，我们还可以在配置文件使用 spring.datasource.druid.filter.* 
#对这些 Filter 进行配置
#        ---------------------------------------------------------------------------
# 在配置 Druid 内置 Filter 时，需要先将对应 Filter 的 enabled 设置为 true，否则内置 Filter 的配置不会生效  
#        ---------------------------------------------------------------------------
# 对配置已开启的 filters 即 stat(sql 监控)  wall（防火墙）
# 配置 StatFilter (SQL监控配置)
      filter:
        stat:
          # 开启 SQL 监控
          enabled: true
          # 慢查询
          slow-sql-millis: 1000
          # 记录慢查询 SQL
          log-slow-sql: true

# 配置 WallFilter (防火墙配置)
        wall:
          # 开启防火墙
          enabled: true
          config:
            # 允许更新操作
            update-allow: true
            # 禁止删表操作
            drop-table-allow: false
            # 允许插入操作
            insert-allow: true
            # 删除数据操作
            delete-allow: true


#  config:
#    activate:
#      on-profile: dev


